# Generated by Django 4.2.6 on 2024-11-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0002_userprogress_has_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='consecutive_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='last_attempt_revealed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='revealed_count',
            field=models.IntegerField(default=0),
        ),
    ]
